### ISSUE TITLE
Can not show image

### ISSUE THREAD

**Issue by Dangtrungphu** [csdcorp/local_image_provider#34]
I can not show image from code example. pls help me. tks
result path (filename): /external/images/media

![flutter_01](https://user-images.githubusercontent.com/40323522/103136455-2a8fda80-46f3-11eb-84d1-5dff580b93db.png)

**Comment by sowens-csd** [comment]
I assume this is on Android? On a real device or the simulator? 

Have you tried other images? Sometimes the problem is as simple as a corrupted image.

**Comment by Dangtrungphu** [comment]
Thanks for the quick reply, i was use real device and  the simulator. 

I was run project example work well. But i paste code this example into the my project is fail image.

I think maybe due to code native my project with package.

**Comment by sowens-csd** [comment]
So you copied the example code into your project and it's not working? The image that's showing there is what happens when the local image can't be located or can't be read. Both of those are unusual problems so I'm surprised you're seeing it on two different devices. Could you post a code snippet or something so I can see how you're using it?

**Comment by sowens-csd** [comment]
Any update on this?

**Comment by Dangtrungphu** [comment]
@sowens-csd , I am sorry to this delay. 
Reason is due my foolishness, i was use link dose not exist in my device.

Thank you for your help. I will close this PR.
